print('=== Your Adventure Simulator ===')
print('''You'll be asked a bunch of questions then we'll make you up an amazing story with You as the star!''')
print()
name = input('your name:')
enemyName = input('your worst enemy\'s name:')
superPower = input('Your super power:')
home = input('where do you live:')
favFood = input('your favorite food:')
print()
print('Our story begins as our Hero', name, 'approaches a forboding castle...')
print('Suddenly a bolt of lightening struck the ground at the feet of', name)
print('Our final battle begins! shouts the evil', enemyName, 'clearly missing the fact that', name, 'has the power of'
      , superPower, 'which means they\'ll win quite easily')
print("Uh, oh, you've been given a", "\033[31m", "warning", "\033[0m", "for being a bad, bad person.")